### ISSUE TITLE
"We'll be back soon for the Kubernetes 10th anniversary party!"

### ISSUE THREAD

**Issue by craigbox** [cncf/contribcard#28]
https://contribcard.clotributor.dev/ has a static message saying "We'll be back soon for the Kubernetes 10th anniversary party!".

Is this expected?  It isn't reflected in the repo anywhere, the site covers more than just Kubernetes, and the 10th anniversary is some months away.

**Comment by tegioz** [comment]
Thanks for your interest in ContribCard @craigbox, the site is back online 🙂
