### ISSUE TITLE
Add WeChat social share link

### ISSUE THREAD

**Issue by caniszczyk** [cncf/contribcard#42]
We should support WeChat in the social share links given how large our China community is

**Comment by tegioz** [comment]
Hi @caniszczyk

WeChat does not seem to provide an easy mechanism to share links like other social networks do. We could add a copy link option to make it easier for WeChat users (and others probably) to take it to the app and share it.

**Comment by tegioz** [comment]
Copy link option added in #44. 

Will close this issue for now, feel free to reopen if needed 🙂
