### ISSUE TITLE
Add LinkedIn to social sharing

### ISSUE THREAD

**Issue by caniszczyk** [cncf/contribcard#45]
We should support LinkedIn too.

Twitter/X + LinkedIn will be the most popular imho

@tegioz if you can try to get this in by this Friday that would be great

**Comment by tegioz** [comment]
Sure, no problem 👍

We already have it actually, but we are hiding it in the smaller versions of the card (i.e. mobile) when not all options fit. We'll swap it for another one for now.

**Comment by tegioz** [comment]
Done in #46 and deployed!
