### ISSUE TITLE
Incomplete contributions

### ISSUE THREAD

**Issue by marcofranssen** [cncf/contribcard#47]
Somehow majority of my contributions is missing on contribcard. E.g. I'm sure I contributed at least 5 more PRs on  the spire repo. And even more on the spire helm charts.

**Comment by tegioz** [comment]
Hi @marcofranssen 👋

Please note that ContribCard is only scanning the repositories in the following organizations for contributions:

<https://github.com/cncf/contribcard-sites/blob/main/kubernetes/settings.yml>

That list should cover most of the repositories of the Kubernetes project.

Hope this helps 🙂

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂

**Comment by marcofranssen** [comment]
Gotcha, that explains majority of my CNCF projects are not counted. Thanks for pointing this out.
