### ISSUE TITLE
404 on serve

### ISSUE THREAD

**Issue by tisonkun** [cncf/contribcard#51]
Reproduce:

```
# Clone the code, and ...
$ cargo build --release
$ ./target/release/contribcard serve
2024-06-13T00:41:01.554386Z  INFO serve: contribcard::serve: http server running (press ctrl+c to stop)

🔗 contribcard available at: http://127.0.0.1:8000
```

```
$ curl -i -X GET  http://127.0.0.1:8000
HTTP/1.1 404 Not Found
Connection: keep-alive
Date: Thu, 13 Jun 2024 00:41:13 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Content-Length: 0
```

Anything I forget to set or configure?

**Comment by tegioz** [comment]
Hi @tisonkun 👋

The `serve` subcommand just launches an HTTP server and serves the provided content directory (or the current one if omitted). It's meant to be used as an easy way to serve the resulting static content of the `build` subcommand:

```
% contribcard build --output-dir my-dir ...
% contribcard serve --content-dir my-dir

**Comment by tisonkun** [comment]
I can prepare a patch and there is already https://github.com/cncf/contribcard/pull/54 for other improvements :D

**Comment by tegioz** [comment]
> Then I have an idea to improve the UX here, we can either:
> 
> 1. Require to specify `--content-dir`
> 2. Warning on fallback to `env::current_dir()` and print what the `current_dir` resolve to
> 3. Warning or error on `let index_path = content.join("index.html");` is not exist with more precise message.

No worries!

Option 2 sounds good to me. Maybe an `info` line displaying the `content_dir` we are using to serve content from is enough.
